language: python
python:
  - 2.7
services:
  - mongodb

env:
  matrix:
  - TOXENV=py27
  global:
    secure: Ekia2KJJD6x+1mNk5uKGnzKO4Jgh8mQE+ExvKAmkIbpJYugWb7dv+zeO8ldiEk8OuqXB+UAXn1Ls1tMAMujIAmsV2f132PPrYJgcRCVeS89A6buESYEgHMNMQBOllknZwyFYHy4IwpMr0HbAl20s7CG4EXGuP7cmCv0gZT1qT/YSUYD+UjbraatLM74HH/I8CMYQT/3J6ndaSjlxz3NFav/8KwdNgV150toYxZBpNx7WDdQk+yo2Jw8dhAMSC8rhnV3Mf5qFdVX1KdtcVEnH5E8s2tAiDXM21Zp0ZIFcVv6ZeNu7svNXUJdG3VxRBIbrYUBWk2BmF5NAVivjIMc//rOA8X1XneGyC/4SoXVZVOtuvDkGEj1yWhhX8esxlZI0HeZjsrMu3NL0/DHGR5NGmYu/xxiaqNvm+enzQoiyld6SwlZh7PBBstL+UvM20ThB0YddVQbxNyFhLMsxq5mDouqHCrfu3wU/Tlac71HpfClPF5D6VGzwhqg2WNC7dAkIa9qL/+peW1EpalOXoktSn0dwNOuFm3B7RmUHlH9drz3nyXRZFODOXZ51gfUK52yQDqYBLZeGpJ47nFJR1A4dAfs0dREzI6GbbR1jjSxiqEkQnlmR/1yndZG7+7P6xX2k/j+80aefLTl3EF5Mpv2fYdI7WngmUYMn2455JqZ/03A=

cache: pip

install:
- pip install -U tox

script:
- tox

notifications:
  slack: crim-ca:A7jqt2VJWnPwN6A3AZXJ40gt

deploy:
  provider: pypi
  distributions: bdist_wheel
  user: crim-ca
  password:
    secure: eMaJJqaOERRV93YsNsRi6+SMSCZj0wGgQkCtwd/pGbI220m8KgSJi+9wFNqABREJQNuWDOTZ6iqZR0XPXyUnWczUhrskPGhGS1d1QyohnHU4OhVVQ0SFdAnxsY5kBwztL5dT0JUfafgqI9hGKY37pyB5YmFR/UwOZL6+bdfFeyqRn0SaGTlGlEsNcLlTUDhBnm+Bx9CmQQa6u+e3bfrV3kTlEF+kUxKbfL1FslZ4QMpv6soUWDqWn8iTgAf+5lMqeywijNXh+/Cv4jwVQwe2DLDU+FfaulQ/8bxjem4RvCwtduZ0D1iIJDWSGJdTbuU3uTlYt8yBEqNSCqj3ciTPVQNwHNUdGpIgQLboFfuU6guOoYbLC9SaqpnQ3zc91xWUBr0BV3liFhLkstu/lPeXt/EnyH4n5Tj8SmpV8xducRbAh/EMGFlxPYh8Fw35P++eXkMZ1ZSWMU0h0nEniNs577vw5DprJ22ebbwfIMMRSeWroWMpIN6MgKOxwLj5dxQACLkHPbZH9XGaLMqAoFo0vAnwVu23kt8yvhkVZdyEKIHSdaUzFYYWnOJaWYPHfPdH3TG8qhtvvBC8c3iRW0YQ7Xe5ywy9IeKinQEJTeLCs+eD27XI2qNz0QEA/y/3qf9g55HMXfyr/v4O4papo7ebzs986KSh1i3q4Wj1++jzAPg=
  on:
    tags: true
